version: '3.9'
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: pfm
      POSTGRES_PASSWORD: pfm
      POSTGRES_DB: pfm
    ports: ["5432:5432"]
    volumes: [pfmdb:/var/lib/postgresql/data]

  api:
    build: ./apps/api
    environment:
      JWT_SECRET: change-me
      NODE_ENV: production
    ports: ["4000:4000"]
    depends_on: [db]
    volumes:
      - ./apps/api/uploads:/app/uploads

  web:
    build: ./apps/web
    environment:
      VITE_API_URL: http://localhost:4000
    ports: ["5173:80"]
    depends_on: [api]

volumes:
  pfmdb:
